//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Create.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Create::genText(const DrTemplateData& Create_view_data)
{
	drogon::OStringStream Create_tmp_stream;
	std::string layoutName{""};
	Create_tmp_stream << "<!DOCTYPE html>\n";
	Create_tmp_stream << "<html>\n";
    auto para=Create_view_data.get<std::unordered_map<std::string,std::string>>("parameters");
	Create_tmp_stream << "<head>\n";
	Create_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	Create_tmp_stream << "    <title>";
{
    auto & val=Create_view_data["title"];
    if(val.type()==typeid(const char *)){
        Create_tmp_stream<<*any_cast<const char *>(&val);
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        Create_tmp_stream<<*any_cast<const std::string>(&val);
    }
}
	Create_tmp_stream << "</title>\n";
	Create_tmp_stream << "</head>\n";
	Create_tmp_stream << "<body>\n";
	Create_tmp_stream << "</body>\n";
	Create_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(Create_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Create_view_data;
auto str = std::move(Create_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
