//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Edit:public drogon::DrTemplate<Edit>
{
public:
	Edit(){};
	virtual ~Edit(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
