//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class View:public drogon::DrTemplate<View>
{
public:
	View(){};
	virtual ~View(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
